name: Deploy Terraform resource
inputs:
  module:
    required: true
    description: Terraform module to apply
runs:
  using: composite
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ env.GCP_CREDENTIALS_JSON }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.12.2

    - name: Initialize Terraform
      shell: bash
      run: terraform init
      working-directory: terraform

    - name: Apply Terraform
      shell: bash
      run: terraform apply -target module.${{ inputs.target }} -auto-approve
      working-directory: terraform
      env:
        TF_VAR_image_name: ${{ env.IMAGE_NAME }}
        TF_VAR_notification_topic: ${{ env.NOTIFICATION_TOPIC }}
        TF_VAR_project_id: ${{ env.GCP_PROJECT_ID }}
        TF_VAR_project_name: ${{ env.PROJECT_NAME }}
        TF_VAR_region: ${{ env.REGION }}