name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: deploy

env:
  GCP_PROJECT_ID: massive-incline-463501-d5
  IMAGE_NAME: app
  PROJECT_NAME: job-posting-notifier
  REGION: us-central1

jobs:
  deploy_artifactory:
    name: Deploy artifactory
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        name: Check for changes
        with:
          filters: |
            infrastructure:
              - 'terraform/*'
              - 'terraform/modules/foundation/**'

      - name: Run action
        if: steps.changes.outputs.infrastructure == 'true'
        uses: ./.github/actions/deploy_terraform_resource
        with:
          module: foundation
        env:
          GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
          GCP_PROJECT_ID: ${{ env.GCP_PROJECT_ID }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          NOTIFICATION_TOPIC: ${{ secrets.NOTIFICATION_TOPIC }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          REGION: ${{ env.REGION }}

  build_and_publish:
    needs: deploy_artifactory
    name: Build & publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        name: Check for changes
        with:
          filters: |
            application:
              - 'Dockerfile'
              - 'pom.xml'
              - 'src/main/**'

      - name: Set up JDK
        if: steps.changes.outputs.application == 'true'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Maven
        if: steps.changes.outputs.application == 'true'
        run: mvn -B clean package

      - name: Authenticate to GCP
        if: steps.changes.outputs.application == 'true'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Set up Google Cloud CLI
        if: steps.changes.outputs.application == 'true'
        uses: google-github-actions/setup-gcloud@v2

      - name: Authenticate Docker with Artifact Registry
        if: steps.changes.outputs.application == 'true'
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build Docker image
        if: steps.changes.outputs.application == 'true'
        run: |
          docker build -t $REGION-docker.pkg.dev/$GCP_PROJECT_ID/$PROJECT_NAME/$IMAGE_NAME:latest .

      - name: Publish Docker image
        if: steps.changes.outputs.application == 'true'
        run: |
          docker push $REGION-docker.pkg.dev/$GCP_PROJECT_ID/$PROJECT_NAME/$IMAGE_NAME:latest

  deploy_instance:
    needs: build_and_publish
    name: Deploy instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        name: Check for changes
        with:
          filters: |
            application:
              - 'Dockerfile'
              - 'pom.xml'
              - 'src/main/**'
            infrastructure:
              - 'terraform/*'
              - 'terraform/modules/runtime/**'

      - name: Run action
        if: ${{ steps.changes.outputs.application == 'true' || steps.changes.outputs.infrastructure == 'true' }}
        uses: ./.github/actions/deploy_terraform_resource
        with:
          module: runtime
        env:
          GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
          GCP_PROJECT_ID: ${{ env.GCP_PROJECT_ID }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          NOTIFICATION_TOPIC: ${{ secrets.NOTIFICATION_TOPIC }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          REGION: ${{ env.REGION }}