name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: deploy

env:
  GCP_PROJECT_ID: massive-incline-463501-d5
  IMAGE_NAME: app
  PROJECT_NAME: api-change-notifier
  REGION: us-central1

jobs:
  deploy_repository:
    name: Deploy repository
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/deploy_terraform_resource
        with:
          target: google_artifact_registry_repository.docker
        env:
          GCP_PROJECT_ID: ${{ env.GCP_PROJECT_ID }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          REGION: ${{ env.REGION }}
        secrets:
          GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
          NOTIFICATION_TOPIC: ${{ secrets.NOTIFICATION_TOPIC }}

  build_and_publish:
    needs: deploy_repository
    name: Build & publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Maven
        run: mvn -B clean package

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Authenticate Docker with Artifact Registry
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build -t $REGION-docker.pkg.dev/$GCP_PROJECT_ID/$PROJECT_NAME/$IMAGE_NAME:latest .

      - name: Publish Docker image
        run: |
          docker push $REGION-docker.pkg.dev/$GCP_PROJECT_ID/$PROJECT_NAME/$IMAGE_NAME:latest

  deploy_instance:
    needs: build_and_publish
    name: Deploy instance
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/deploy_terraform_resource
        with:
          target: google_compute_instance.app
        env:
          GCP_PROJECT_ID: ${{ env.GCP_PROJECT_ID }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          REGION: ${{ env.REGION }}
        secrets:
          GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
          NOTIFICATION_TOPIC: ${{ secrets.NOTIFICATION_TOPIC }}